"""A fixture this repo can rebuild must not also be committed.

ISSUE #13 SAID SO AND THE INDEX SAID OTHERWISE. Its acceptance reads "every
fixture generated idempotently on a clean checkout, none committed", while ten
generatable .mp4 files sat in git. The contradiction had been noticed once
before and resolved by editing the DOCSTRING to admit the files were tracked --
which made the prose honest and left the criterion unmet.

THAT WAS NOT COSMETIC. Untracking them exposed a real defect the binaries had
been hiding for as long as they existed: `test_model_guard_ratchet.py` built
bare paths (`FIXTURES / "base6.mp4"`) and never called a generator. On a cold
checkout it failed 15 of its 16 renders and created nothing -- reproduced twice
in the full suite and once in isolation. Every other cold run passed, so the
whole suite had been silently depending on binaries nobody could rebuild.

So the rule is enforced here rather than remembered. Adding a generatable
fixture back to the index fails this test.

WHAT IS DELIBERATELY EXEMPT, because neither is generated by `tests/fixtures.py`:

  talk.mp4 / meeting.mp4      built by tests/speech_fixtures.py, which needs
  (+ their .groundtruth.json) espeak-ng -- a system dependency beyond ffmpeg.

  openai_tts/sample.wav       a RECORDED REAL RESPONSE with provenance in
  (+ sample.json)             sample.json. This repo requires a substitute to
                              be a replay of a real run, never a hand-written
                              mock, so this one MUST be committed.
"""

from __future__ import annotations

from pathlib import Path
import subprocess

import pytest

ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = Path("tests/fixtures")

#: Committed on purpose. Every entry needs a reason that is about being
#: UNGENERATABLE here, not about convenience.
#: MEDIA ONLY. The `.groundtruth.json` and `sample.json` files beside these are
#: text, so `_tracked_fixture_media` never considers them and listing them here
#: would make the staleness check below fail -- which it did, immediately, on the
#: first run of this file.
ALLOWED_COMMITTED = {
    "tests/fixtures/talk.mp4",
    "tests/fixtures/meeting.mp4",
    "tests/fixtures/openai_tts/sample.wav",
}

#: Binary media. Text under tests/fixtures/ (ground truth, provenance) is fine.
MEDIA_SUFFIXES = {".mp4", ".mov", ".mkv", ".webm", ".wav", ".mp3", ".png", ".jpg", ".jpeg"}


def _tracked_fixture_media() -> set[str]:
    """Ask git what is tracked, or SKIP saying so -- never pass by default.

    This shells out, so it cannot answer everywhere. `scripts/ci-parity.sh`
    bind-mounts the repo into a container under a different uid and git refuses
    with exit 128 ("dubious ownership"), which failed this file on its first
    distro run. A test that cannot obtain its evidence must say that plainly:
    failing blames the code for the environment, and passing would assert a
    clean index nobody looked at. GitHub Actions checks out normally, so the
    guard is genuinely enforced where merges happen.
    """
    try:
        out = subprocess.run(
            ["git", "ls-files", str(FIXTURE_DIR)],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError:
        pytest.skip("git is not on PATH, so the index cannot be inspected here")
    except subprocess.CalledProcessError as exc:
        pytest.skip(
            f"git could not read this checkout (exit {exc.returncode}); "
            f"typically a container bind-mount under another uid: {exc.stderr.strip()[:120]}"
        )
    return {
        line.strip()
        for line in out.stdout.splitlines()
        if line.strip() and Path(line.strip()).suffix.lower() in MEDIA_SUFFIXES
    }


def test_generated_fixtures_are_not_committed() -> None:
    offenders = sorted(_tracked_fixture_media() - ALLOWED_COMMITTED)

    assert not offenders, (
        "these fixture binaries are tracked in git but are rebuilt by "
        "tests/fixtures.py's ensure_* helpers, so committing them stores "
        "regenerable bytes AND lets a test depend on a file it never generates:\n  "
        + "\n  ".join(offenders)
        + "\n\nEither delete them (and add to .gitignore), or, if genuinely "
        "ungeneratable here, add them to ALLOWED_COMMITTED with the reason."
    )


def test_the_exempt_files_actually_exist() -> None:
    """A guard whose allow-list has gone stale guards less than it claims."""
    tracked = _tracked_fixture_media()
    missing = sorted(ALLOWED_COMMITTED - tracked)

    assert not missing, (
        f"ALLOWED_COMMITTED names {missing}, which are no longer tracked. "
        "Remove them from the allow-list so it keeps describing reality."
    )


def test_the_detector_would_catch_a_recommitted_fixture() -> None:
    """A guard that cannot fire guards nothing."""
    pretend_tracked = {"tests/fixtures/base6.mp4", *ALLOWED_COMMITTED}
    offenders = pretend_tracked - ALLOWED_COMMITTED

    assert offenders == {"tests/fixtures/base6.mp4"}, (
        "the detector does not recognise a re-committed generatable fixture"
    )
